In [1]:
import numpy as np

In [2]:
seed = np.random.default_rng(3)
arr = seed.integers(1, 10, (3, 3))
arr

array([[8, 1, 2],
       [3, 2, 8],
       [8, 6, 1]], dtype=int64)

# Thuộc tính

In [3]:
print(arr.shape)  # mảng 2 chiều chứa 3 mảng 1 chiều, mỗi mảng chứa 3 phần tử
print(arr.size)  # tổng phần tử 3x3
print(arr.ndim)  # số chiều

(3, 3)
9
2


# ÉP KIỂU DỮ LIỆU

In [4]:
float_arr = arr.astype(float)  # others: complex, ...
float_arr

array([[8., 1., 2.],
       [3., 2., 8.],
       [8., 6., 1.]])

# THAY ĐỔI SHAPE

In [5]:
reshaped_arr = arr.reshape(9, -1)
# mảng 2 chiều gồm 9 mảng 1 chiều, mỗi mảng chứa ... phần tử
reshaped_arr

array([[8],
       [1],
       [2],
       [3],
       [2],
       [8],
       [8],
       [6],
       [1]], dtype=int64)

In [15]:
flattened_arr = reshaped_arr.flatten()
flattened_arr

array([8, 1, 2, 3, 2, 8, 8, 6, 1], dtype=int64)

# Sắp xếp

In [6]:
sort_column = np.sort(arr, axis=0)
sort_column

array([[3, 1, 1],
       [8, 2, 2],
       [8, 6, 8]], dtype=int64)

In [7]:
sort_row = np.sort(arr, axis=1)
sort_row

array([[1, 2, 8],
       [2, 3, 8],
       [1, 6, 8]], dtype=int64)

In [8]:
reverse_sort_row = -np.sort(-arr, axis=1)  
# sắp xếp tăng dần th arr ÂM và thêm dấu - để đổi ngược lại thành arr DƯƠNG
reverse_sort_row

array([[8, 2, 1],
       [8, 3, 2],
       [8, 6, 1]], dtype=int64)

# Thêm

In [9]:
append_flatten = np.append(arr, [[100], [100], [100]], axis=None)
append_flatten

array([  8,   1,   2,   3,   2,   8,   8,   6,   1, 100, 100, 100],
      dtype=int64)

In [10]:
append_row = np.append(arr, [[100, 100, 100]], axis=0)
append_row

array([[  8,   1,   2],
       [  3,   2,   8],
       [  8,   6,   1],
       [100, 100, 100]], dtype=int64)

In [11]:
append_column = np.append(arr, [[100], [100], [100]], axis=1)
append_column

array([[  8,   1,   2, 100],
       [  3,   2,   8, 100],
       [  8,   6,   1, 100]], dtype=int64)

# Xóa

In [12]:
delete_flatten = np.delete(append_flatten, [0, 1, 2], axis=None)
delete_flatten

array([  3,   2,   8,   8,   6,   1, 100, 100, 100], dtype=int64)

In [13]:
delete_column = np.delete(append_column, 1, axis=1)  # index 3 of column
delete_column

array([[  8,   2, 100],
       [  3,   8, 100],
       [  8,   1, 100]], dtype=int64)

In [14]:
delete_row = np.delete(append_row, 2, axis=0)  # index 2 of row
delete_row

array([[  8,   1,   2],
       [  3,   2,   8],
       [100, 100, 100]], dtype=int64)