In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.linear_model as lm
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

### PREPARE DATA

In [2]:
df = pd.read_excel('score.xlsx',sheet_name='Sheet2')
print(df)
print('-'*100)

# đầu vào
X = df[['so_gio_hoc', 'do_tap_trung', 'pp_hoc', 'tuoi']].values

# đầu ra
Y = df.diem.values

# Chia X,Y thành 2 bộ training & testing
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,train_size = 0.6, random_state=42)
print(X_train)
print()
print(X_test)
print('-'*100)
print(Y_train)
print()
print(Y_test)

   so_gio_hoc  do_tap_trung  pp_hoc  tuoi  diem
0           2             5       1    20    30
1           3             4       2    25    35
2           4             2       4    40    40
3           5             4       3    30    44
4           6             2       2    20    48
5           7             3       2    30    60
6           8             5       1    30    66
7           9             2       3    50    70
8          10             1       2    15    75
----------------------------------------------------------------------------------------------------
[[10  1  2 15]
 [ 4  2  4 40]
 [ 6  2  2 20]
 [ 5  4  3 30]
 [ 8  5  1 30]]

[[ 9  2  3 50]
 [ 3  4  2 25]
 [ 7  3  2 30]
 [ 2  5  1 20]]
----------------------------------------------------------------------------------------------------
[75 40 48 44 66]

[70 35 60 30]


### SELECT & TRAIN MODEL

In [3]:
# SELECT
LR = lm.LinearRegression()

# TRAIN
LR.fit(X_train,Y_train)

# CHECK QUY TẮC: y = a.x + b.y + c.z + d.e + f
a = LR.coef_
b = LR.intercept_
print('coefficients:',a)
print('intercept:',b)

coefficients: [ 7.17647059e+00  2.35780287e-15 -2.35294118e-01  3.41176471e-01]
intercept: -1.4117647058823835


### TEST

In [4]:
Yp_train = LR.predict(X_train)

In [5]:
Yp_test = LR.predict(X_test)

### EVALUATE MODEL

In [6]:
MSE1 = mean_squared_error(Y_test,Yp_test) # hay variance
MSE2 = mean_squared_error(Y_train,Yp_train)
print('MSE OF TESTING DATA:',MSE1)
print('MSE OF TRAINING DATA:',MSE2)
print('-'*100)

R2_1 = r2_score(Y_test,Yp_test) # R_squared
R2_2 = r2_score(Y_train,Yp_train)
print('R2 OF TESTING DATA:',R2_1)
print('R2 OF TRAINING DATA:',R2_2)
print('-'*100)

# KẾT LUẬN
print('==> OVERFIT')


# MAE,MSE,RMSE gần về 0 càng tốt
# R2 gần về 1 càng tốt

MSE OF TESTING DATA: 62.24913494809691
MSE OF TRAINING DATA: 1.8175355256292112e-28
----------------------------------------------------------------------------------------------------
R2 OF TESTING DATA: 0.7774332605207708
R2 OF TRAINING DATA: 1.0
----------------------------------------------------------------------------------------------------
==> OVERFIT


### IMPLEMENT

In [7]:
Y_moi = LR.predict([[15,3,2,50]])
print(Y_moi)

[122.82352941]
