In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
digit = load_digits()
digit

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [4]:
dir(digit)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [5]:
df = pd.DataFrame(digit.data, columns=digit.feature_names)
df['target'] = digit.target
df['target_names'] = df.target.apply(lambda x: digit.target_names[x])
df

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_7_0  pixel_7_1  \
0           0.0        0.0        0.0        0.0  ...        0.0        0.0   
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
2           0.0        0.0        0.0        0.0  ...        0.0        0.0   
3           0.0        0.0        0.0        8.0  ...        0.0        0.0   
4           0.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1792        0.0        0.0        0.0        1.0  ...        0.0        0.0   
1793        1.0        0.0        0.0        0.0  ...        0.0        0.0   
1794        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1796        0.0        0.0        0.0        2.0  ...        0.0        1.0   

      pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  pixel_7_7  \
0           6.0       13.0       10.0        0.0        0.0        0.0   
1           0.0       11.0       16.0       10.0        0.0        0.0   
2           0.0        3.0       11.0       16.0        9.0        0.0   
3           7.0       13.0       13.0        9.0        0.0        0.0   
4           0.0        2.0       16.0        4.0        0.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        2.0       14.0       15.0        9.0        0.0        0.0   
1793        6.0       16.0       14.0        6.0        0.0        0.0   
1794        2.0        9.0       13.0        6.0        0.0        0.0   
1795        5.0       12.0       16.0       12.0        0.0        0.0   
1796        8.0       12.0       14.0       12.0        1.0        0.0   

      target  target_names  
0          0             0  
1          1             1  
2          2             2  
3          3             3  
4          4             4  
...      ...           ...  
1792       9             9  
1793       0             0  
1794       8             8  
1795       9             9  
1796       8             8  

[1797 rows x 66 columns]

In [6]:
df.target.value_counts()

target
3    183
1    182
5    182
4    181
6    181
9    180
7    179
0    178
2    177
8    174
Name: count, dtype: int64

In [7]:
1797 / 5

359.4

# Difference between KFold and StratifiedKFold

In [8]:
# KFold không nên dùng do hoàn toàn lấy theo thứ tự, và không lấy class theo tỉ lệ, 
# có thể trong 1 lần lấy, thì lại toàn class 0 hoặc 1 thì sao???
k_fold = KFold(n_splits=5, shuffle=True, random_state=0)
print(k_fold)
print()

for train_index, test_index in k_fold.split(digit.data, digit.target):
    print(train_index.shape, test_index.shape)
    
    Y_train = digit.target[train_index]
    Y_test = digit.target[test_index]

    print(np.unique(Y_train, return_counts=True))
    print(np.unique(Y_test, return_counts=True))
  
    print('~'*100)

# ĐỂ Ý COUNTS CỦA TỪNG CLASS CỦA Y_TRAIN KÌA TRONG CẢ 5 LẦN KÌA!!!

KFold(n_splits=5, random_state=0, shuffle=True)

(1437,) (360,)
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([151, 147, 141, 154, 151, 142, 137, 140, 135, 139], dtype=int64))
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([27, 35, 36, 29, 30, 40, 44, 39, 39, 41], dtype=int64))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(1437,) (360,)
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([145, 144, 142, 142, 148, 133, 148, 153, 135, 147], dtype=int64))
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([33, 38, 35, 41, 33, 49, 33, 26, 39, 33], dtype=int64))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(1438,) (359,)
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([131, 147, 146, 138, 143, 147, 152, 146, 143, 145], dtype=int64))
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([47, 35, 31, 45, 38, 35, 29, 33, 31, 35], dtype=int64))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [9]:
# trong 1 lấy lấy thì lấy các class chia theo tỉ lệ với số lần xuất hiện của từng class trong dataset 
stratified_k_fold = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
print(stratified_k_fold)
print()

for train_index, test_index in stratified_k_fold.split(digit.data, digit.target):
    print(train_index.shape, test_index.shape)
    
    Y_train = digit.target[train_index]
    Y_test = digit.target[test_index]

    print(np.unique(Y_train, return_counts=True))
    print(np.unique(Y_test, return_counts=True))
  
    print('~'*100)
    
# ĐỂ Ý COUNTS CỦA TỪNG CLASS CỦA Y_TRAIN KÌA TRONG CẢ 5 LẦN KÌA!!!

StratifiedKFold(n_splits=5, random_state=0, shuffle=True)

(1437,) (360,)
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([142, 146, 141, 147, 144, 146, 145, 143, 139, 144], dtype=int64))
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([36, 36, 36, 36, 37, 36, 36, 36, 35, 36], dtype=int64))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(1437,) (360,)
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([142, 146, 141, 147, 145, 145, 145, 143, 139, 144], dtype=int64))
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([36, 36, 36, 36, 36, 37, 36, 36, 35, 36], dtype=int64))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(1438,) (359,)
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([142, 146, 142, 146, 145, 145, 145, 143, 140, 144], dtype=int64))
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([36, 36, 35, 37, 36, 37, 36, 36, 34, 36], dtype=int64))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Now, It's time for coding

In [10]:
def model_score(model, X_train, Y_train, X_test, Y_test):
    model.fit(X_train, Y_train)
    return model.score(X_test, Y_test)

In [11]:
lor = LogisticRegression()
svc = SVC()
rfc = RandomForestClassifier(n_estimators=33)

In [12]:
scores_lor = []
scores_svc = []
scores_rfc = []

In [13]:
skf = StratifiedKFold(n_splits=5)

for train_index, test_index in skf.split(digit.data, digit.target):
    X_train, X_test, Y_train, Y_test = digit.data[train_index], digit.data[test_index], \
                                    digit.target[train_index], digit.target[test_index]
    
    scores_lor.append(model_score(lor, X_train, Y_train, X_test, Y_test))  
    scores_svc.append(model_score(svc, X_train, Y_train, X_test, Y_test))  
    scores_rfc.append(model_score(rfc, X_train, Y_train, X_test, Y_test))  

In [14]:
print(scores_lor)
print(scores_svc)
print(scores_rfc)

[0.9222222222222223, 0.8694444444444445, 0.9415041782729805, 0.9387186629526463, 0.8969359331476323]
[0.9611111111111111, 0.9444444444444444, 0.9832869080779945, 0.9888579387186629, 0.9387186629526463]
[0.9138888888888889, 0.9027777777777778, 0.9526462395543176, 0.9637883008356546, 0.9052924791086351]


In [15]:
from statistics import mean
print(mean(scores_lor))
print(mean(scores_svc))
print(mean(scores_rfc))

0.9137650882079852
0.9632838130609719
0.9276787372330548


### Using sklearn.model_selection.cross_val_score

In [16]:
X = digit.data
Y = digit.target

In [17]:
print(cross_val_score(lor, X, Y, cv=5))  # return an array of scores of the testing set
print(cross_val_score(svc, X, Y, cv=5))
print(cross_val_score(rfc, X, Y, cv=5))

[0.92222222 0.86944444 0.94150418 0.93871866 0.89693593]
[0.96111111 0.94444444 0.98328691 0.98885794 0.93871866]
[0.92777778 0.89444444 0.94428969 0.97771588 0.91364903]


In [18]:
print(cross_val_score(lor, X, Y, cv=5).mean())
print(cross_val_score(svc, X, Y, cv=5).mean())
print(cross_val_score(rfc, X, Y, cv=5).mean())

0.9137650882079852
0.9632838130609718
0.929896316929743
