In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
digit = load_digits()
dir(digit)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
df = pd.DataFrame(digit.data,columns=digit.feature_names)
df['target'] = digit.target
df['target_names'] = df.target.apply(lambda x:digit.target_names[x])
df

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_7_0  pixel_7_1  \
0           0.0        0.0        0.0        0.0  ...        0.0        0.0   
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
2           0.0        0.0        0.0        0.0  ...        0.0        0.0   
3           0.0        0.0        0.0        8.0  ...        0.0        0.0   
4           0.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1792        0.0        0.0        0.0        1.0  ...        0.0        0.0   
1793        1.0        0.0        0.0        0.0  ...        0.0        0.0   
1794        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1796        0.0        0.0        0.0        2.0  ...        0.0        1.0   

      pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  pixel_7_7  \
0           6.0       13.0       10.0        0.0        0.0        0.0   
1           0.0       11.0       16.0       10.0        0.0        0.0   
2           0.0        3.0       11.0       16.0        9.0        0.0   
3           7.0       13.0       13.0        9.0        0.0        0.0   
4           0.0        2.0       16.0        4.0        0.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        2.0       14.0       15.0        9.0        0.0        0.0   
1793        6.0       16.0       14.0        6.0        0.0        0.0   
1794        2.0        9.0       13.0        6.0        0.0        0.0   
1795        5.0       12.0       16.0       12.0        0.0        0.0   
1796        8.0       12.0       14.0       12.0        1.0        0.0   

      target  target_names  
0          0             0  
1          1             1  
2          2             2  
3          3             3  
4          4             4  
...      ...           ...  
1792       9             9  
1793       0             0  
1794       8             8  
1795       9             9  
1796       8             8  

[1797 rows x 66 columns]

In [5]:
df.describe()

pixel_0_0    pixel_0_1    pixel_0_2    pixel_0_3    pixel_0_4  \
count     1797.0  1797.000000  1797.000000  1797.000000  1797.000000   
mean         0.0     0.303840     5.204786    11.835838    11.848080   
std          0.0     0.907192     4.754826     4.248842     4.287388   
min          0.0     0.000000     0.000000     0.000000     0.000000   
25%          0.0     0.000000     1.000000    10.000000    10.000000   
50%          0.0     0.000000     4.000000    13.000000    13.000000   
75%          0.0     0.000000     9.000000    15.000000    15.000000   
max          0.0     8.000000    16.000000    16.000000    16.000000   

         pixel_0_5    pixel_0_6    pixel_0_7    pixel_1_0    pixel_1_1  ...  \
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000  ...   
mean      5.781859     1.362270     0.129661     0.005565     1.993879  ...   
std       5.666418     3.325775     1.037383     0.094222     3.196160  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       4.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%      11.000000     0.000000     0.000000     0.000000     3.000000  ...   
max      16.000000    16.000000    15.000000     2.000000    16.000000  ...   

         pixel_7_0    pixel_7_1    pixel_7_2    pixel_7_3    pixel_7_4  \
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000   
mean      0.000556     0.279354     5.557596    12.089037    11.809126   
std       0.023590     0.934302     5.103019     4.374694     4.933947   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     1.000000    11.000000    10.000000   
50%       0.000000     0.000000     4.000000    13.000000    14.000000   
75%       0.000000     0.000000    10.000000    16.000000    16.000000   
max       1.000000     9.000000    16.000000    16.000000    16.000000   

         pixel_7_5    pixel_7_6    pixel_7_7       target  target_names  
count  1797.000000  1797.000000  1797.000000  1797.000000   1797.000000  
mean      6.764051     2.067891     0.364496     4.490818      4.490818  
std       5.900623     4.090548     1.860122     2.865304      2.865304  
min       0.000000     0.000000     0.000000     0.000000      0.000000  
25%       0.000000     0.000000     0.000000     2.000000      2.000000  
50%       6.000000     0.000000     0.000000     4.000000      4.000000  
75%      12.000000     2.000000     0.000000     7.000000      7.000000  
max      16.000000    16.000000    16.000000     9.000000      9.000000  

[8 rows x 66 columns]

In [6]:
X = digit.data

scaler = StandardScaler().set_output(transform='pandas')

X_scaled = scaler.fit_transform(X)
X_scaled

x0        x1        x2        x3        x4        x5        x6  \
0     0.0 -0.335016 -0.043081  0.274072 -0.664478 -0.844129 -0.409724   
1     0.0 -0.335016 -1.094937  0.038648  0.268751 -0.138020 -0.409724   
2     0.0 -0.335016 -1.094937 -1.844742  0.735366  1.097673 -0.409724   
3     0.0 -0.335016  0.377661  0.744919  0.268751 -0.844129 -0.409724   
4     0.0 -0.335016 -1.094937 -2.551014 -0.197863 -1.020657 -0.409724   
...   ...       ...       ...       ...       ...       ...       ...   
1792  0.0 -0.335016 -0.253452 -0.432200  0.268751  0.038508 -0.409724   
1793  0.0 -0.335016  0.167290  0.980343  0.268751  0.921145 -0.108958   
1794  0.0 -0.335016 -0.884566 -0.196776  0.735366 -0.844129 -0.409724   
1795  0.0 -0.335016 -0.674195 -0.432200 -1.131092 -1.020657 -0.409724   
1796  0.0 -0.335016  1.008775  0.509495 -0.897785 -0.844129 -0.409724   

            x7        x8        x9  ...       x54       x55       x56  \
0    -0.125023 -0.059078 -0.624009  ... -0.757436 -0.209785 -0.023596   
1    -0.125023 -0.059078 -0.624009  ... -0.757436 -0.209785 -0.023596   
2    -0.125023 -0.059078 -0.624009  ...  0.259230 -0.209785 -0.023596   
3    -0.125023 -0.059078  1.879691  ...  1.072563 -0.209785 -0.023596   
4    -0.125023 -0.059078 -0.624009  ... -0.757436 -0.209785 -0.023596   
...        ...       ...       ...  ...       ...       ...       ...   
1792 -0.125023 -0.059078 -0.311047  ...  0.055897 -0.209785 -0.023596   
1793 -0.125023 -0.059078 -0.624009  ... -0.554103 -0.209785 -0.023596   
1794 -0.125023 -0.059078 -0.624009  ... -0.757436 -0.209785 -0.023596   
1795 -0.125023 -0.059078 -0.624009  ... -0.350769 -0.209785 -0.023596   
1796 -0.125023 -0.059078  0.001916  ...  0.869229 -0.209785 -0.023596   

           x57       x58       x59       x60       x61       x62       x63  
0    -0.299081  0.086719  0.208293 -0.366771 -1.146647 -0.505670 -0.196008  
1    -0.299081 -1.089383 -0.249010  0.849632  0.548561 -0.505670 -0.196008  
2    -0.299081 -1.089383 -2.078218 -0.164037  1.565686  1.695137 -0.196008  
3    -0.299081  0.282736  0.208293  0.241430  0.379040 -0.505670 -0.196008  
4    -0.299081 -1.089383 -2.306869  0.849632 -0.468564 -0.505670 -0.196008  
...        ...       ...       ...       ...       ...       ...       ...  
1792 -0.299081 -0.697349  0.436944  0.646898  0.379040 -0.505670 -0.196008  
1793 -0.299081  0.086719  0.894246  0.444164 -0.129523 -0.505670 -0.196008  
1794 -0.299081 -0.697349 -0.706312  0.241430 -0.129523 -0.505670 -0.196008  
1795 -0.299081 -0.109298 -0.020358  0.849632  0.887602 -0.505670 -0.196008  
1796  0.771535  0.478753 -0.020358  0.444164  0.887602 -0.261136 -0.196008  

[1797 rows x 64 columns]

# Training without PCA

In [7]:
Y = digit.target

X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, train_size=0.8, random_state=0)
X_train.shape, X_test.shape

((1437, 64), (360, 64))

In [8]:
np.unique(Y_train, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([151, 147, 141, 154, 151, 142, 137, 140, 135, 139], dtype=int64))

In [9]:
lor = LogisticRegression()
lor.fit(X_train, Y_train)

lor.score(X_train, Y_train), lor.score(X_test, Y_test)

(0.9986082115518441, 0.9611111111111111)

# Training using PCA

*1. Scale features before applying PCA*

*2. Score might drop*

In [10]:
pca = PCA(n_components=16).set_output(transform='pandas')

X_reduced = pca.fit_transform(X_scaled)
X_reduced

pca0      pca1      pca2      pca3      pca4      pca5      pca6  \
0     1.914206 -0.954475 -3.946223  2.028902 -0.268485  0.528963 -1.414339   
1     0.589000  0.924576  3.924916 -1.780387 -0.991443 -0.673040  1.877266   
2     1.302050 -0.317188  3.023380 -2.043313 -2.081668  0.934751 -1.297490   
3    -3.020785 -0.868720 -0.801705 -2.187193 -0.556070  0.727621  0.960003   
4     4.528949 -1.093502  0.973242 -1.419339 -1.714724  1.432221  1.073482   
...        ...       ...       ...       ...       ...       ...       ...   
1792  0.104330  0.254970 -3.765667 -1.946963 -0.188682 -0.554962  0.531319   
1793  2.423230 -1.429547 -3.045357  2.631928 -0.824146  0.003674 -1.107632   
1794  1.022604 -0.147960  2.470205 -0.620475 -0.970402 -0.005674  0.380100   
1795  1.076065 -0.381022 -2.455046 -1.312152  0.257477 -0.635780  1.035080   
1796 -1.257696 -2.227642  0.284013 -0.127178 -1.566937  2.346070 -0.383438   

          pca7      pca8      pca9     pca10     pca11     pca12     pca13  \
0     1.491497  0.122313 -0.819017 -0.516278 -0.775398  0.212572 -0.198760   
1     0.559379  1.085520  0.070074 -0.483606  0.641683 -0.034564 -0.388995   
2     1.153535  0.789826 -1.091079  2.190339 -2.321311 -0.543683 -1.002491   
3    -1.378216  0.255531  0.741518 -1.063559  0.488316 -0.166155  1.014567   
4    -0.964204 -1.660189  1.176453 -1.011708 -1.375791 -0.340461 -0.092298   
...        ...       ...       ...       ...       ...       ...       ...   
1792  0.479673  1.149406 -0.476300 -0.613424  0.788309  1.206067 -0.679385   
1793  2.332345  0.574341 -1.653993 -0.474123 -0.518418  0.873037  0.859234   
1794  0.533266  2.055211 -2.044134 -0.655853  0.382704 -0.395930  0.273663   
1795  0.769407  1.070832 -0.344866 -0.937858  0.577787  0.163692 -0.724536   
1796 -1.192362  0.811534 -1.828458 -0.048433  0.518919  0.103414  0.830636   

         pca14     pca15  
0     0.861974  0.110491  
1    -0.740218 -0.187920  
2    -1.160434  0.355541  
3    -0.170417 -0.985926  
4     0.716612  0.212952  
...        ...       ...  
1792  0.170602  0.175154  
1793 -0.701398  1.034541  
1794  0.309174  1.150030  
1795 -0.019118  0.222704  
1796  1.780382  0.276951  

[1797 rows x 16 columns]

In [11]:
pca.n_features_

64

In [12]:
pca.explained_variance_.shape, pca.explained_variance_

((16,),
 array([7.34477606, 5.83549053, 5.15396108, 3.9662359 , 2.96633844,
        2.57203904, 2.40600847, 2.06864035, 1.82992113, 1.78944516,
        1.69718758, 1.57254191, 1.38855207, 1.35853104, 1.32083008,
        1.16657376]))

In [13]:
variance_ratio = pca.explained_variance_ratio_
variance_ratio

array([0.12033916, 0.09561054, 0.08444415, 0.06498408, 0.04860144,
       0.04214111, 0.03942081, 0.03389327, 0.02998201, 0.02931884,
       0.02780726, 0.02576503, 0.02275048, 0.02225861, 0.0216409 ,
       0.01911352])

In [14]:
np.sum(variance_ratio)

0.7280712149326671

In [15]:
Y = digit.target

X_train, X_test, Y_train, Y_test = train_test_split(X_reduced, Y, train_size=0.6,random_state=0)
X_train.shape, X_test.shape

((1078, 16), (719, 16))

In [16]:
np.unique(Y_train, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([118, 109, 106, 113, 118,  93, 105, 114,  96, 106], dtype=int64))

In [17]:
lor = LogisticRegression()
lor.fit(X_train, Y_train)

lor.score(X_train, Y_train), lor.score(X_test, Y_test)

(0.9730983302411874, 0.933240611961057)