In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

In [2]:
digit = load_digits()
dir(digit)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
print(digit.data.shape)
digit.data

(1797, 64)


array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [4]:
print(len(digit.feature_names))
digit.feature_names

64


['pixel_0_0',
 'pixel_0_1',
 'pixel_0_2',
 'pixel_0_3',
 'pixel_0_4',
 'pixel_0_5',
 'pixel_0_6',
 'pixel_0_7',
 'pixel_1_0',
 'pixel_1_1',
 'pixel_1_2',
 'pixel_1_3',
 'pixel_1_4',
 'pixel_1_5',
 'pixel_1_6',
 'pixel_1_7',
 'pixel_2_0',
 'pixel_2_1',
 'pixel_2_2',
 'pixel_2_3',
 'pixel_2_4',
 'pixel_2_5',
 'pixel_2_6',
 'pixel_2_7',
 'pixel_3_0',
 'pixel_3_1',
 'pixel_3_2',
 'pixel_3_3',
 'pixel_3_4',
 'pixel_3_5',
 'pixel_3_6',
 'pixel_3_7',
 'pixel_4_0',
 'pixel_4_1',
 'pixel_4_2',
 'pixel_4_3',
 'pixel_4_4',
 'pixel_4_5',
 'pixel_4_6',
 'pixel_4_7',
 'pixel_5_0',
 'pixel_5_1',
 'pixel_5_2',
 'pixel_5_3',
 'pixel_5_4',
 'pixel_5_5',
 'pixel_5_6',
 'pixel_5_7',
 'pixel_6_0',
 'pixel_6_1',
 'pixel_6_2',
 'pixel_6_3',
 'pixel_6_4',
 'pixel_6_5',
 'pixel_6_6',
 'pixel_6_7',
 'pixel_7_0',
 'pixel_7_1',
 'pixel_7_2',
 'pixel_7_3',
 'pixel_7_4',
 'pixel_7_5',
 'pixel_7_6',
 'pixel_7_7']

In [5]:
print(digit.images.shape)
digit.images[0]

(1797, 8, 8)


array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [6]:
print(digit.target.shape)
digit.target

(1797,)


array([0, 1, 2, ..., 8, 9, 8])

In [7]:
print(digit.target_names.shape)
digit.target_names

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
pd.set_option('display.max_rows', None)
df = pd.DataFrame(digit.data,columns=digit.feature_names)
df['target'] = digit.target
df['target_names'] = df.target.apply(lambda x:digit.target_names[x])
df

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
5           0.0        0.0       12.0       10.0        0.0        0.0   
6           0.0        0.0        0.0       12.0       13.0        0.0   
7           0.0        0.0        7.0        8.0       13.0       16.0   
8           0.0        0.0        9.0       14.0        8.0        1.0   
9           0.0        0.0       11.0       12.0        0.0        0.0   
10          0.0        0.0        1.0        9.0       15.0       11.0   
11          0.0        0.0        0.0        0.0       14.0       13.0   
12          0.0        0.0        5.0       12.0        1.0        0.0   
13          0.0        2.0        9.0       15.0       14.0        9.0   
14          0.0        0.0        0.0        8.0       15.0        1.0   
15          0.0        5.0       12.0       13.0       16.0       16.0   
16          0.0        0.0        0.0        8.0       15.0        1.0   
17          0.0        0.0        1.0        8.0       15.0       10.0   
18          0.0        0.0       10.0        7.0       13.0        9.0   
19          0.0        0.0        6.0       14.0        4.0        0.0   
20          0.0        0.0        3.0       13.0       11.0        7.0   
21          0.0        0.0        0.0        2.0       16.0       16.0   
22          0.0        0.0        8.0       16.0        5.0        0.0   
23          0.0        1.0        8.0       12.0       15.0       14.0   
24          0.0        0.0        0.0        0.0       12.0        2.0   
25          0.0        0.0       12.0        8.0        8.0        7.0   
26          0.0        0.0        1.0       13.0       14.0        3.0   
27          0.0        0.0        0.0        8.0       14.0       14.0   
28          0.0        0.0       10.0       11.0        4.0        0.0   
29          0.0        0.0        9.0       13.0        7.0        0.0   
30          0.0        0.0       10.0       14.0       11.0        3.0   
31          0.0        0.0        2.0       13.0        8.0        0.0   
32          0.0        2.0       13.0       16.0       16.0       16.0   
33          0.0        6.0       13.0        5.0        8.0        8.0   
34          0.0        0.0        0.0        5.0       14.0        2.0   
35          0.0        3.0       15.0        8.0        8.0        6.0   
36          0.0        0.0        6.0       14.0       10.0        2.0   
37          0.0        0.0       13.0       10.0        1.0        0.0   
38          0.0        0.0        7.0        7.0       13.0       16.0   
39          0.0        1.0        9.0       16.0       13.0        7.0   
40          0.0        0.0       11.0       10.0       12.0        4.0   
41          0.0        0.0        0.0        9.0       15.0        1.0   
42          0.0        0.0        0.0        0.0       12.0        5.0   
43          0.0        0.0        0.0        9.0       15.0       12.0   
44          0.0        0.0        9.0       16.0       16.0       16.0   
45          0.0        0.0        9.0       16.0       13.0        6.0   
46          0.0        1.0       15.0        4.0        0.0        0.0   
47          0.0        0.0        0.0        1.0       11.0        9.0   
48          0.0        0.0        2.0       15.0       13.0        3.0   
49          0.0        0.0        1.0       15.0       13.0        1.0   
50          0.0        0.0        0.0        5.0       14.0       12.0   
51          0.0        0.0        0.0        3.0       15.0       10.0   
52          0.0        0.0        3.0       12.0       16.0       16.0   
53        

In [9]:
X = digit.data
Y = digit.target
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,train_size=0.7,random_state=1)
print(len(X_train))
print(len(X_test))

1257
540


# SVC

##### kernel='rbf'

In [10]:
svc = SVC()
svc.fit(X_train,Y_train)

SVC()

In [11]:
Yp_train = svc.predict(X_train)
print(svc.score(X_train,Y_train))

0.9952267303102625


In [12]:
Yp_test = svc.predict(X_test)
print(svc.score(X_test,Y_test))

0.9851851851851852


##### kernel='linear'

In [13]:
svc = SVC(kernel='linear')
svc.fit(X_train,Y_train)

SVC(kernel='linear')

In [14]:
Yp_train = svc.predict(X_train)
print(svc.score(X_train,Y_train))

1.0


In [15]:
Yp_test = svc.predict(X_test)
print(svc.score(X_test,Y_test))

0.9814814814814815
