In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
digit = load_digits()
dir(digit)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
df = pd.DataFrame(digit.data, columns=digit.feature_names)
df['target'] = digit.target
df['target_names'] = df.target.apply(lambda x:digit.target_names[x])
df

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_7_0  pixel_7_1  \
0           0.0        0.0        0.0        0.0  ...        0.0        0.0   
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
2           0.0        0.0        0.0        0.0  ...        0.0        0.0   
3           0.0        0.0        0.0        8.0  ...        0.0        0.0   
4           0.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1792        0.0        0.0        0.0        1.0  ...        0.0        0.0   
1793        1.0        0.0        0.0        0.0  ...        0.0        0.0   
1794        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1796        0.0        0.0        0.0        2.0  ...        0.0        1.0   

      pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  pixel_7_7  \
0           6.0       13.0       10.0        0.0        0.0        0.0   
1           0.0       11.0       16.0       10.0        0.0        0.0   
2           0.0        3.0       11.0       16.0        9.0        0.0   
3           7.0       13.0       13.0        9.0        0.0        0.0   
4           0.0        2.0       16.0        4.0        0.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        2.0       14.0       15.0        9.0        0.0        0.0   
1793        6.0       16.0       14.0        6.0        0.0        0.0   
1794        2.0        9.0       13.0        6.0        0.0        0.0   
1795        5.0       12.0       16.0       12.0        0.0        0.0   
1796        8.0       12.0       14.0       12.0        1.0        0.0   

      target  target_names  
0          0             0  
1          1             1  
2          2             2  
3          3             3  
4          4             4  
...      ...           ...  
1792       9             9  
1793       0             0  
1794       8             8  
1795       9             9  
1796       8             8  

[1797 rows x 66 columns]

In [5]:
df.describe()

pixel_0_0    pixel_0_1    pixel_0_2    pixel_0_3    pixel_0_4  \
count     1797.0  1797.000000  1797.000000  1797.000000  1797.000000   
mean         0.0     0.303840     5.204786    11.835838    11.848080   
std          0.0     0.907192     4.754826     4.248842     4.287388   
min          0.0     0.000000     0.000000     0.000000     0.000000   
25%          0.0     0.000000     1.000000    10.000000    10.000000   
50%          0.0     0.000000     4.000000    13.000000    13.000000   
75%          0.0     0.000000     9.000000    15.000000    15.000000   
max          0.0     8.000000    16.000000    16.000000    16.000000   

         pixel_0_5    pixel_0_6    pixel_0_7    pixel_1_0    pixel_1_1  ...  \
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000  ...   
mean      5.781859     1.362270     0.129661     0.005565     1.993879  ...   
std       5.666418     3.325775     1.037383     0.094222     3.196160  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       4.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%      11.000000     0.000000     0.000000     0.000000     3.000000  ...   
max      16.000000    16.000000    15.000000     2.000000    16.000000  ...   

         pixel_7_0    pixel_7_1    pixel_7_2    pixel_7_3    pixel_7_4  \
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000   
mean      0.000556     0.279354     5.557596    12.089037    11.809126   
std       0.023590     0.934302     5.103019     4.374694     4.933947   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     1.000000    11.000000    10.000000   
50%       0.000000     0.000000     4.000000    13.000000    14.000000   
75%       0.000000     0.000000    10.000000    16.000000    16.000000   
max       1.000000     9.000000    16.000000    16.000000    16.000000   

         pixel_7_5    pixel_7_6    pixel_7_7       target  target_names  
count  1797.000000  1797.000000  1797.000000  1797.000000   1797.000000  
mean      6.764051     2.067891     0.364496     4.490818      4.490818  
std       5.900623     4.090548     1.860122     2.865304      2.865304  
min       0.000000     0.000000     0.000000     0.000000      0.000000  
25%       0.000000     0.000000     0.000000     2.000000      2.000000  
50%       6.000000     0.000000     0.000000     4.000000      4.000000  
75%      12.000000     2.000000     0.000000     7.000000      7.000000  
max      16.000000    16.000000    16.000000     9.000000      9.000000  

[8 rows x 66 columns]

In [6]:
X = digit.data
Y = digit.target

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.6, random_state=0)
X_train.shape, X_test.shape

((1078, 64), (719, 64))

In [8]:
np.unique(Y_train, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([118, 109, 106, 113, 118,  93, 105, 114,  96, 106], dtype=int64))

# Training

In [9]:
knn = KNeighborsClassifier(n_neighbors=3, weights='distance', metric='minkowski', p=2)
knn.fit(X_train, Y_train)

knn.score(X_train, Y_train), knn.score(X_test, Y_test)

(1.0, 0.9888734353268428)

In [10]:
Yp_test = knn.predict(X_test)
confusion_matrix(Y_test, Yp_test)

array([[60,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 73,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 71,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 70,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 62,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0, 87,  1,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0, 76,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 65,  0,  0],
       [ 0,  2,  0,  1,  0,  0,  0,  0, 74,  1],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  0, 73]], dtype=int64)

# Check wrong

In [11]:
df2 = pd.DataFrame(X_test, columns=digit.feature_names)
df2['target'] = Y_test
df2['target_test'] = Yp_test
df2

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0          0.0        0.0       11.0       16.0       15.0        3.0   
1          0.0        1.0       15.0       14.0        2.0        0.0   
2          0.0        2.0       13.0       16.0       10.0        0.0   
3          0.0        0.0        9.0        7.0        0.0        0.0   
4          0.0        0.0        3.0       13.0        6.0        0.0   
..         ...        ...        ...        ...        ...        ...   
714        0.0        0.0        3.0       13.0       16.0       16.0   
715        0.0        3.0       11.0       15.0       12.0        7.0   
716        0.0        2.0       15.0       15.0        3.0        0.0   
717        0.0        0.0        1.0       11.0       16.0       16.0   
718        0.0        0.0        2.0        9.0       15.0       12.0   

     pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_7_0  pixel_7_1  \
0          0.0        0.0        0.0        5.0  ...        0.0        0.0   
1          0.0        0.0        0.0        6.0  ...        0.0        1.0   
2          0.0        0.0        0.0       12.0  ...        0.0        1.0   
3          0.0        0.0        0.0        0.0  ...        0.0        0.0   
4          0.0        0.0        0.0        0.0  ...        0.0        0.0   
..         ...        ...        ...        ...  ...        ...        ...   
714       13.0        0.0        0.0        0.0  ...        0.0        0.0   
715        1.0        0.0        0.0        4.0  ...        0.0        5.0   
716        0.0        0.0        0.0       11.0  ...        0.0        2.0   
717       10.0        0.0        0.0        0.0  ...        0.0        0.0   
718        5.0        0.0        0.0        0.0  ...        0.0        0.0   

     pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  pixel_7_7  target  \
0         13.0       13.0        8.0       13.0       16.0        8.0       2   
1         15.0       16.0       12.0        1.0        0.0        0.0       8   
2         13.0       16.0       16.0       16.0       16.0        3.0       2   
3          7.0       14.0       16.0       12.0        1.0        0.0       6   
4          3.0       13.0       15.0        8.0        0.0        0.0       6   
..         ...        ...        ...        ...        ...        ...     ...   
714        2.0       15.0        4.0        0.0        0.0        0.0       7   
715       13.0        6.0        0.0        0.0        0.0        0.0       5   
716       13.0       14.0       12.0       12.0        8.0        1.0       2   
717        0.0       13.0        3.0        0.0        0.0        0.0       7   
718        0.0       10.0       13.0        2.0        0.0        0.0       8   

     target_test  
0              2  
1              8  
2              2  
3              6  
4              6  
..           ...  
714            7  
715            5  
716            2  
717            7  
718            8  

[719 rows x 66 columns]

In [12]:
df2_diff = df2[df2.target != df2.target_test]
df2_diff

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
169        0.0        0.0        4.0       11.0       14.0        4.0   
181        0.0        0.0       12.0       10.0        0.0        0.0   
315        0.0        0.0        1.0       14.0        8.0        8.0   
472        0.0        0.0        4.0        9.0       13.0       13.0   
507        0.0        0.0        4.0        6.0       11.0        5.0   
548        0.0        0.0        1.0        8.0       13.0        1.0   
577        0.0        1.0       11.0       16.0       11.0        1.0   
584        0.0        0.0        0.0        2.0       15.0        5.0   

     pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_7_0  pixel_7_1  \
169        0.0        0.0        0.0        5.0  ...        0.0        0.0   
181        0.0        0.0        0.0        0.0  ...        0.0        0.0   
315        1.0        0.0        0.0        0.0  ...        0.0        0.0   
472        0.0        0.0        0.0        1.0  ...        0.0        0.0   
507        0.0        0.0        0.0        2.0  ...        0.0        0.0   
548        0.0        0.0        0.0        0.0  ...        0.0        0.0   
577        0.0        0.0        0.0        6.0  ...        0.0        0.0   
584        0.0        0.0        0.0        0.0  ...        0.0        0.0   

     pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  pixel_7_7  target  \
169        2.0       15.0       16.0       15.0        4.0        0.0       8   
181        9.0       16.0       16.0       10.0        0.0        0.0       5   
315        0.0       12.0        0.0        0.0        0.0        0.0       4   
472        3.0       12.0       14.0        8.0        0.0        0.0       5   
507        6.0       10.0       11.0        7.0        1.0        0.0       8   
548        0.0        5.0       12.0        5.0        0.0        0.0       8   
577       14.0        8.0        4.0        0.0        0.0        0.0       9   
584        0.0        2.0       14.0       11.0        0.0        0.0       8   

     target_test  
169            3  
181            9  
315            7  
472            6  
507            9  
548            1  
577            3  
584            1  

[8 rows x 66 columns]