In [1]:
from tensorflow import keras
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [3]:
tf.test.is_built_with_cuda()

False

### https://keras.io/api/datasets/cifar10/

In [4]:
(X_train, y_train), (X_test, y_test) = keras.datasets.cifar10.load_data()

In [5]:
X_train.shape, y_train.shape

((50000, 32, 32, 3), (50000, 1))

In [6]:
X_test.shape, y_test.shape

((10000, 32, 32, 3), (10000, 1))

In [7]:
np.unique(y_test, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8),
 array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
       dtype=int64))

# Data Manipulation

In [8]:
X_train_scaled = X_train / 255
X_test_scaled = X_test /255

In [9]:
y_train_encoded = keras.utils.to_categorical(y_train, num_classes=10)
y_test_encoded = keras.utils.to_categorical(y_test, num_classes=10)

y_train_encoded.shape, y_train_encoded

((50000, 10),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.]]))

# Build Model

In [17]:
def nn_adam():
    model = keras.Sequential([
        keras.layers.Input(shape=(32, 32, 3)),  # 32x32x3 = 3072
        keras.layers.Flatten(),
        keras.layers.Dense(300, activation='relu'),
        keras.layers.Dense(10, activation='softmax')])

    model.compile(optimizer='adam',
                 loss='categorical_crossentropy',
                 metrics=['accuracy'])
    
    return model

In [14]:
def nn_sgd():
    model = keras.Sequential([
        keras.layers.Input(shape=(32, 32, 3)),  # 32x32x3 = 3072
        keras.layers.Flatten(),
        keras.layers.Dense(300, activation='relu'),
        keras.layers.Dense(10, activation='softmax')])

    model.compile(optimizer='SGD',
                 loss='categorical_crossentropy',
                 metrics=['accuracy'])
    
    return model

# Train Model on CPU

### Bài này chuẩn phải dùng CNN nhé. Dùng NN để test thôi nka!

In [15]:
%%timeit -n1 -r1  # to display the time it took to run
with tf.device('/CPU:0'):
    model_on_CPU = nn_sgd()
    model_on_CPU.fit(X_train_scaled, y_train_encoded, epochs=5)

Epoch 1/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.2848 - loss: 1.9814
Epoch 2/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.3937 - loss: 1.7227
Epoch 3/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.4243 - loss: 1.6330
Epoch 4/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.4459 - loss: 1.5802
Epoch 5/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.4584 - loss: 1.5336
50.3 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [18]:
%%timeit -n1 -r1  # to display the time it took to run
with tf.device('/CPU:0'):
    model_on_CPU = nn_adam()
    model_on_CPU.fit(X_train_scaled, y_train_encoded, epochs=5)

Epoch 1/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 27s 16ms/step - accuracy: 0.2789 - loss: 2.0614
Epoch 2/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 24s 16ms/step - accuracy: 0.3718 - loss: 1.7485
Epoch 3/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 24s 15ms/step - accuracy: 0.4009 - loss: 1.6826
Epoch 4/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 24s 15ms/step - accuracy: 0.4143 - loss: 1.6371
Epoch 5/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 23s 15ms/step - accuracy: 0.4353 - loss: 1.6067
2min 3s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


---

# Train Model on GPU

In [ ]:
%%timeit -n1 -r1  # to display the time it took to run
with tf.device('/GPU:0'):
    model_on_CPU = nn_sgd()
    model_on_CPU.fit(X_train_scaled, y_train_encoded, epochs=5)

In [ ]:
%%timeit -n1 -r1  # to display the time it took to run
with tf.device('/GPU:0'):
    model_on_CPU = nn_adam()
    model_on_CPU.fit(X_train_scaled, y_train_encoded, epochs=5)